### ISSUE TITLE
Activity Recreation Issue

### ISSUE THREAD

**Issue by umutyusuf** [Trendyol/medusa#12]
On rotation, navigator adds root fragment over existing one. Might be resolved by optionally passing savedInstanceState

**Comment by iammert** [comment]
Will be open an issue for it. Rotation support is a must. Thanks. @umutyusuf

**Comment by erkutaras** [comment]
Activity recreation issue has been fixed on v0.7.0. With this version, implementation of navigator is changed, you can find updated implementation on [wiki](https://github.com/Trendyol/medusa/wiki/Basic-Usage).  If you find any bug, feel free to report or open PR :) Thanks for supports.
