### ISSUE TITLE
Failed to resolve: com.github.Trendyol.medusa:0.2:

### ISSUE THREAD

**Issue by tieorange** [Trendyol/medusa#16]
Can't fetch Medusa.

Yes, I've added:
`maven { url "https://jitpack.io" }`
to `repositories`

**Comment by erkutaras** [comment]
can you try `implementation 'implementation 'com.github.Trendyol.medusa:medusalib:0.2'` ?

Now you can use `implementation 'com.github.Trendyol:medusa:0.4'`
