### ISSUE TITLE
Feature Request: Destroy All Fragments

### ISSUE THREAD

**Issue by efekanegeli** [Trendyol/medusa#27]
I want to change all of the tabs if a user is logged in / made an in app purchase etc.

I created a new rootFragmentProvider and multipleStackNavigator for this purpose, however there should be an option for clearing/removing all of the old fragments. Without this feature, the old ones are still visible after the tab items' change.

**Comment by MertNYuksel** [comment]
https://github.com/Trendyol/medusa/pull/28
