### ISSUE TITLE
getrootfragment function access modifier

### ISSUE THREAD

**Issue by maqtay** [Trendyol/medusa#52]
There are 5 tabs in the app. When the user clicks the back button on some of these tabs, I want to raise an alert without looking at the stack and close the application when the user clicks on this alert. How can I do this? An idea came to my mind, but since the getrootfragment function is private, I cannot access this function and control the tab. Would it be a problem to make this private function public?

**Comment by bilgehankalkan** [comment]
You can use `NavigatorListener` interface. This interface will invoke `onTabChanged` with tab index.

Both `MainActivity` and `MainActivity2` on `:app` provides sample implementations for this interface.
