### ISSUE TITLE
Not working after Progaurd, minify true

### ISSUE THREAD

**Issue by 133usr** [Trendyol/medusa#54]
The fragement attach detach is not working after enabling minify.
Thanks

**Comment by 133usr** [comment]
Already tried adding 
```
-dontwarn com.trendyol.**
-keep class com.trendyol.* {*;}
-keep interface com.trendyol.* { *;}
```
int he progaurd.pro

**Comment by bilgehankalkan** [comment]
Hello,

I tried enabling minify on sample project (`:app`) and couldn't reproduce any errors related to minify. Also we're using `Medusa` on our internal projects and never had an issue with it.

If you can share your project -or at least part of the project that I can reproduce the error- I'll take a look on the issue and try to come up with a solution.

**Comment by 133usr** [comment]
Yeah right, the issue was regarding my own static vars and methods; Thankyou so much for replying .
