### ISSUE TITLE
Fragment transition

### ISSUE THREAD

**Issue by iammert** [Trendyol/medusa#7]
Animations/Transitions are not supported yet. Medusa library can take an animator to switch between fragments. 

So Medusa library can take in and out animation from outside and apply these animations when the transaction is committed.

**Comment by SubhrajyotiSen** [comment]
How should this API be designed? Should it be a function that passes 2 anim files (enter and exit) to medusa?

**Comment by iammert** [comment]
We did not decide it yet. But probably, It will have a similar syntax with fragment transaction API in the Android Framework.

**Comment by SubhrajyotiSen** [comment]
We are planning to use Medusa for one of our apps and would like transition animations. If the API design is decided, maybe we can contribute the solution we come up with

**Comment by mertceyhan** [comment]
Is there any working about this issue?

**Comment by iammert** [comment]
Not yet. PRs are welcome about this issue.

**Comment by selimtoksal** [comment]
**Fragment transitions** is available starting from `v0.8.0`
left to right, right to left, bottom to top, top to bottom, fade in out variants are support for now
Api with custom animation resource is next goal
We'll be delighted to review any PRs with custom animation, feel free to contribute
